import type { NextPage } from 'next';
import styled from 'styled-components';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import EvolutionOverview from '@components/ui/EvolutionOverview';

const Evolution: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Admin Dashboard</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="preload"
					href="/fonts/Pixelar/Pixelar-Regular-W01-Regular.ttf"
					as="font"
					crossOrigin=""
				/>
			</Head>
			<EvolutionOverview />
		</div>
	);
};

export default Evolution;
