import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import styled from 'styled-components';
import Container from '../components/ui/Container';
import Sidebar from '../components/common/Sidebar';

const MainContent = styled.div``;

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Hello BB fam</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="preload"
					href="/fonts/Pixelar/Pixelar-Regular-W01-Regular.ttf"
					as="font"
					crossOrigin=""
				/>
			</Head>

			<main className={styles.main}>
				<Sidebar />
				<Container />
			</main>
		</div>
	);
};

export default Home;
